// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLjb6lknvyW8gw_5eG8tBv6Vm-hMt2rY',
    appId: '1:1025345835550:web:25d822109b60e46b98140f',
    messagingSenderId: '1025345835550',
    projectId: 'post-express-780dd',
    authDomain: 'post-express-780dd.firebaseapp.com',
    storageBucket: 'post-express-780dd.appspot.com',
    measurementId: 'G-L5DEHT463H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQYeYrOW_J3w0cZVHDeukZRYwVYa7ehg',
    appId: '1:1025345835550:android:5f04d395d53df8d198140f',
    messagingSenderId: '1025345835550',
    projectId: 'post-express-780dd',
    storageBucket: 'post-express-780dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6r9F7By2gJuE7TwraEEnVQxpRjVF264',
    appId: '1:1025345835550:ios:3f51c9c2db8103ba98140f',
    messagingSenderId: '1025345835550',
    projectId: 'post-express-780dd',
    storageBucket: 'post-express-780dd.appspot.com',
    iosClientId: '1025345835550-fggjflmc2j1e0qvlv6a8p5crimrlj7nh.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.wepostexpresscustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6r9F7By2gJuE7TwraEEnVQxpRjVF264',
    appId: '1:1025345835550:ios:3f51c9c2db8103ba98140f',
    messagingSenderId: '1025345835550',
    projectId: 'post-express-780dd',
    storageBucket: 'post-express-780dd.appspot.com',
    iosClientId: '1025345835550-fggjflmc2j1e0qvlv6a8p5crimrlj7nh.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.wepostexpresscustomer',
  );
}
